guanzhi/GmSSL

- doc/apps/pkey.pod
- doc/apps/rand.pod
- doc/apps/s_client.pod
- doc/apps/s_server.pod
- doc/apps/speed.pod
- doc/apps/verify.pod
- doc/apps/x509.pod
> translation upadte

- crypto/gmapi/gmapi_skf_ec.c
delete OPENSSL_assert(sig->r); and OPENSSL_assert(sig->s);
> delete OPENSSL_assert in ECDSA_SIG_set_ECCSIGNATUREBLOB

- Configure
- crypto/gmapi/gmapi_skf_ec.c
Build for mips64 should be mips64r2, not mips3
> Add linux64-mips64 build support with mips64r2.

- crypto/asn1/a_sign.c
> maybe memory leak

- crypto/gmapi/gmapi_sdf_ec.c
remove the repetitive validation of cv->hash
> remove the repetitive validation of cv->hash

- crypto/gmapi/gmapi_sdf_rsa.c
> fix the incorrect free

- crypto/gmapi/gmapi_sdf_rsa.c
> fix the incorrect pexp index

- java/GmSSL.c
added outbuf  buffer releasing step
> fixed memory leak issue

- apps/s_client.c
Add dcert and dkey cli args for s_client to support gmtls testing through s_server and s_client.
Example:
```bash
$ gmssl s_server -accept 4333 -CAfile CA.cert.pem -cert ServerSign.cert.pem -key ServerSign.key.pem -dcert ServerEncrypt.cert.pem -dkey ServerEncrypt.key.pem -gmtls -debug -msg -Verify 1
$ gmssl s_client -connect localhost:4333 -CAfile CA.cert.pem -cert ClientSign.cert.pem -key ClientSign.key.pem -dcert ClientEncrypt.cert.pem -dkey ClientEncrypt.key.pem -showcerts -msg -debug -gmtls -verify 1
```
> Add GM double cert support in s_client

- ssl/statem/statem_gmtls.c
1. 签名使用SM2默认ID：1234567812345678，而不是证书使用者。
2. 修复了被签名的加密证书长度问题，证书有一个3Byte用于容纳长度的空间。在服务端的秘钥交换过程少了3Byte。
可以通过访问 [沃通提供的国密TLS测试网站: sm2test.ovssl.cn](https://sm2test.ovssl.cn/)验证代码正确性。
```c
#include <stdio.h>
#include <openssl/bio.h>
#include <openssl/ssl.h>
#include <openssl/err.h>
#define HOST_PORT "sm2test.ovssl.cn:https"
//#define HOST_PORT "localhost:4433"
int main() {
BIO *sbio, *out;
int len, res;
char tmpbuf[1024];
SSL_CTX *ctx;
SSL *ssl;
ctx = SSL_CTX_new(GMTLS_client_method());
SSL_CTX_set_verify(ctx, SSL_VERIFY_NONE, NULL);
//    res = SSL_CTX_load_verify_locations(ctx, "../cert/wotrushRoot.cer", "../cert/");
//    res = SSL_CTX_load_verify_locations(ctx, "/home/quanguanyu/certs/SS.crt", "/home/quanguanyu/certs/");
if (!res) {
fprintf(stderr, ">> Can't load SSL Root Cert!\n"); …
```
> [bug fix] 修复了ECC_SM4_SM3套件在秘钥交换过程中的错误

- CMakeLists.txt
- include/gmssl/sm9.h
- src/sm9_math.c
- tests/sm9test.c
1. Add prefix sm9_ & SM9_
2. Move functions and defines to sm9.h
3. Add blank sm9test file and modify Cmakefile; working for full sm9test
> modify sm9

- src/sm9_alg.c
- tests/sm9test.c
Add tests: SM9 - fp2, fp4, fp12
Bug fixed: sm9_fp12_pow
> Add tests & Bugs fixed

- src/sm9_alg.c
- tests/sm9test.c
Add test: SM9 - point; move pairing test into function, will pass in this week
Bugs fixed: sm9_fp12_pow, sm9_point_mul, sm9_point_is_at_infinity
> Add test & Bugs fixed

- src/sm9_alg.c
- tests/sm9test.c
Add tests: SM9 - twist_point, pairing
Bug fixed: sm9_twist_point_mul
> Add tests & Bug fixed

- src/sm4_modes.c
- tests/sm4test.c
> fix ctr mode counter, add ctr test

- .gitignore
- src/gf128_avx.c
- tools/sm3speed.c
- tools/sm4speed.c
add gf128_avx.c sm3speed.c sm4speed.c
> add gf128_avx, add sm3 sm4 speed

- Configure
- test/build.info
there's an error when running config script under ubuntu 22.04
> fix config error

- include/gmssl/sm2.h
- src/tlcp.c
支持TLS1.1协议版本与国密实验室双向认证互通测试
相关issues
https://github.com/guanzhi/GmSSL/issues/1352
https://github.com/guanzhi/GmSSL/issues/1271
> support connect demo.gmssl.cn:1443

- src/sm4_rng.c
GMT 0105-2021 软件随机数发生器设计指南中E.4节：
`d) temp=temp⊕seed_material;`
> SM4_RNG_Update增加异或

- CMakeLists.txt
> 增加在nmake下对源文件utf-8编码的支持，解决在msvc编译错误问题

- src/sm2_alg.c
- src/sm2_key.c
> Fix error check sm2_point_is_on_curve
