- README.md
- crypto/skf/skf.h
- crypto/x509/x509_d2.c
- ssl/s3_clnt.c
- ssl/s3_lib.c
- ssl/ssl_ciph.c
- ssl/ssl_lib.c
- ssl/t1_lib.c
说明：
主要使用GMSSL做个项目：
客户端与服务器均使用GMSSL库，客户端位于WIN+MINGW编译环境, 服务端位于Linux +GCC。
问题：
强制双向证书认证+指定SM2套件发现SSL握手失败。
修正：
1、修正Win32+MINGW+MSYS下编译不过
2、使用GMSSL做双向认证发现无法像Wiki说的支持TLS1.x的两个SM2套件， 代码做了调整。
3、去掉非SM2的套件（项目不允许，代码一起带过来了，请忽略）
> TLS.1x标准的SM2双向认证过程发现一些问题 请指正或参考

- README.md
如题。
目前没加-pubin，pkeyutl -verify会把给的vrfykey.pem作为私钥，从而不能正常解析vrfykey.pem。
应增加-pubin，使其把vrfykey.pem作为公钥
> README.md中SM2里pkeyutl -verify例子，应该增加-pubin，否则无法运行。

- crypto/evp/m_sm3.c
[https://github.com/guanzhi/GmSSL/issues/547](url)
> fix: zero length NULL should be able to be used for sm3 digest update.

- engines/sdf_dummy.c
- engines/skf_dummy.c
When build dynamic library on Windows, build errors occur on SKF and SDF
engines build. Because when the engines are compiled into a
self-contained dll, bind_engine and v_check are needed which has been
exported in def file.
Add missing methods here to resolve the build error.
Because the engines are dummy implemented, the methods added here are
also dummy.
Ref：
https://www.openssl.org/blog/blog/2015/11/23/engine-building-lesson-2-an-example-md5-engine/
This build error has been mentioned at issue#399
> Fix SKF and SDF engines build error

- crypto/sm3/sm3.c
- include/openssl/sm3.h
用openssl做参照，测试gmssl的sm3时，发现数据在256MB到512MB之间时（768MB到1024MB同理），二者digest不一致。后来发现如下两点问题：
1.sm3 padding 的程序中有移位操作，count[1] = cpu_to_be32((ctx->nblocks << 9) + (ctx->num << 3));
而ctx->nblocks是一个有符号整型，当其左移后，最高位为1时，该位会被移位到符号位。
当执行cpu_to_be32这个函数时，会进行大小端转换，内部会有右移操作。
由于有符号数和无符号数右移的时候，左边补的数不同，无符号数补0，有符号数补符号位，这就会导致count[1]出现错误。
2.sm3 spec要求，补位的bit len是64位的，所以这里的ctx->nblocks必须要大于64-9=55位，所以修改ctx->nblocks为64位无符号类型。
修改后的代码已经测试了256MB到512MB，768MB到1024MB，以及（2^61-64）byte的几组数据，测试都是正确的
> fix sm3 padding bug

- crypto/sm2/sm2_oct.c
SM2 密文格式转换接口 `o2i_SM2CiphertextValue()` 中对 `cv` 的释放似乎缺少判断，释放的条件为：
1. cv 为接口内部分配的资源
2. 处理过程中发生错误
其他条件则不对 cv 进行释放操作，比如接口外完成的 cv 申请.
> sm2: fix cv free error, in o2i_SM2CiphertextValue() function

- go/gmssl/engine.go
并没有使用ENGINE_new就调用了ENGINE_free，使得程序运行到该析构函数时提示析构了空指针。由于go语言的SetFinalizer函数在程序结束时并不一定会被调用，所以现有程序并不会运行到该行代码，但是现有代码多次运行就会遇到该问题。删除C.ENGINE_free(ret.engine)该行即可解决问题。
> Sm2 bugfix

- crypto/sm2/sm2_oct.c
The caller will crash when using the return value from
o2i_SM2CiphertextValue. Because the returned pointer to SM2CiphertextValue has been free,
regardless of success or failure in this method.
When assign cv to ret, cv should be set NULL just like the behaviour in
SM2_do_encrypt.
> Fix unnecessary free in o2i_SM2CiphertextValue

- Configurations/windows-makefile.tmpl
NMAKE : fatal error U1095: 扩展命令行“del /Q /F  ...... engines\ossltest.dll engines\padlock.dll engines\sdf_dummy.dll engines\skf_dummy.dll apps\CA.pl apps\tsget.pl tools\c_rehash.pl”太长
Stop.  
的错误。
> 修正windows下nmake clean 时命令行太长的错误

- crypto/sm9/sm9_rate.c
在sm9_rate.c的rate函数中，用条件编译可以选择使用原版还是fast的final-expo，选项为SM9-FAST
> fast-final-expo

- crypto/sm2/build.info
fix bug  LNK2001 unresolved external symbol SM2_cosigner1_generate_proof
...
The file crypto\sm2\sm2_cosign. c is not compiled, so add it to build. info
> fix bug LNK2001

- crypto/ec/asm/ecp_sm2z256-x86_64.pl
#951、 #941 等issue提到SM2验签有很小的概率会失败，原因和解决方法如下。
ecp_sm2z256-x86_64.pl中函数__ecp_sm2z256_sqr_montx 1272，1285，1298，1311行使用加法指令adox，在支持BMI2指令的CPU上会造成偶发的验签失败。
原因是这里的加法应该不带进位(参考函数__ecp_sm2z256_sqr_montq 920，936，952，968行，使用的是add指令)，而adox是带进位的（OF=1的时候会加一）。
失败的概率非常低，平均大概几十万次会错一次，这是因为OF是由之前的sbb指令决定的[(sbb)](https://www.felixcloutier.com/x86/sbb)，只有当有符号减法借位时会设OF=1，而实际执行sbb时候是64位整数减32位整数，几乎不可能借位。
在这4个adox指令前加上add \$0, $acc2这类指令就可以设置OF=0，不会再出现偶发的验签失败。
> sm2_bmi2_bugfix

- README.md
{0xe0,0x1a} should be GMTLS_RSA_WITH_SMS4_SHA1
> chore:correct typo

- go/gmssl/pkey.go
- go/gmssltest/gmssltest.go
1. 此map被遍历时出来的元素顺序不固定，会偶尔导致 GeneratePrivateKey 出错。
`
sm2keygenargs := map[string]string {
"ec_paramgen_curve": "sm2p256v1",
"ec_param_enc": "named_curve",
}
sm2sk, _ := gmssl.GeneratePrivateKey("EC", sm2keygenargs, nil)
`
`
140105295136512:error:1010C0B1:elliptic curve routines:pkey_ec_ctrl:no parameters set:crypto/ec/ec_pmeth.c:391
`
改成数组解决问题。
2. 修正内存泄漏若干
> bug fixed: no fixed order in map may cause GeneratePrivateKey error

- test/sm9test.c
sm9_rate.c: L2704~L2754使用宏开关定义rate_test方法，测试用例test/sm9test.c中调用到rate_test方法的位置和定义时保持一致使用SM9_TEST宏开关包起来, 解决编译链接报错的问题。
```
#if SM9_TEST
static int rate_test(void)
{
const char *Ppubs_str[] = {
"29DBA116152D1F786CE843ED24A3B573414D2177386A92DD8F14D65696EA5E32",
"9F64080B3084F733E48AFF4B41B565011CE0711C5E392CFB0AB1B6791B94C408",
"41E00A53DDA532DA1A7CE027B7A46F741006E85F5CDFF0730E75C05FB4E3216D",
"69850938ABEA0112B57329F447E3A0CBAD3E2FDB1A77F335E89E1408D0EF1C25"};
const char *g_str[] = {
"AAB9F06A4EEBA4323A7833DB202E4E35639D93FA3305AF73F0F071D7D284FCFB",
"84B87422330D7936EABA1109FA5A7A7181EE16F2438B0AEB2F38FD5F7554E57A",
"4C744E69C4A2E1C8ED72F796D151A17CE2325B943260FC460B9F73CB57C9014B",
"B3129A75D31D17194675A1BC56947920898FBF390A5BF5D931CE6CBB3340F66D", …
```
> 解决972 issue中的编译链接报错问题

- ssl/statem/statem_gmtls.c
A local var `l` in gmtls_construct_client_certificate is uninitialized,
which leads to an cert length mismatch error.
GMTLS handshake using SM2-WITH-SMS4-SM3 cipher suite will be failed due
to this issue.
My editor automatically removed some trailing spaces when I fixed this
bug. So some lines modified in `statem_gmtls.c` are insignificant.
Please ignore them.
https://github.com/guanzhi/GmSSL/issues/850
> Uninitialized variable `l` results in cert length mismatch error

- crypto/sm3/sm3.c
修复 - SM3 sm3_compute_id_digest 总是进入默认ID分支。
> 修复：SM3 sm3_compute_id_digest 总是进入默认ID分支。

- include/gmssl/sm2.h
本地使用时，在 C++ 项目内引入 `sm2.h` 后报错
看起来是最后的右括号错误
> fix: extern "C" right brace

- tests/cmstest.c
In test case 6 on develop branch, the `siglen` in `test_cms_signer_info()` do not initialize, which makes a segfault. This pull request fixes this by initializing the `siglen` to length of `sig_buf`.
> Fix a segfault for test case #6 (cms)

- Configurations/10-main.conf
- config
- engines/afalg/e_afalg.c
Add compilation support for loongarch64 arch.
Reference link:http://gmssl.org/docs/quickstart.html
test version on loongarch64 arch:
root@loongson-pc:/usr/local/gmssl# gmssl version
GmSSL 2.5.4 - OpenSSL 1.1.0d  19 Jun 2019
Tests are normal，like test SM4、SM3、SM2 and so on.
Examples：
root@loongson-pc:/usr/local/gmssl# lscpu |grep Architecture
Architecture:        loongarch64
root@loongson-pc:/usr/local/ssl-test# gmssl sms4 -e -in test.txt -out test.txt.sms4
enter sms4-cbc encryption password:
Verifying - enter sms4-cbc encryption password:
root@loongson-pc:/usr/local/ssl-test# ls
test.txt  test.txt.sms4
root@loongson-pc:/usr/local/ssl-test# gmssl sms4 -d -in test.txt.sms4 
enter sms4-cbc decryption password:
111111111111123333333333333333455555555555555555555 …
> Add compilation support for loongarch64 arch

- java/GmSSL.c
SM4接口在JNI的封装方法Java_org_gmssl_GmSSL_symmetricEncrypt中outbuf指针的内存未释放，会造成Java应用内存耗尽。
经压测环境验证，在GmSSL/java/GmSSL.c文件补充以下代码可解决内存消耗的问题：
OPENSSL_free(outbuf);
> 修复JNI接口中SM4解密内存管理缺陷

- CMakeLists.txt
补充了缺少的wsock32.lib和Ws2_32.lib以在MinGW上通过编译。
在msys2的UCRT64环境下，使用GCC12.2编译通过。
> fix cmake build error on mingw

- src/sm9_alg.c
根据论文[1]优化了SM9双线性对中的miller loop。根据论文，miller loop性能有5.2%的提升。
[1] Ping Zhen, Xiaobo Hu, Yanyan Yu, Liang Liu, and Haifeng Zhang. 2017. Research on the Optimization Computation of SM9 Bilinear Pairings. In Proceedings of the 2017 2nd International Conference on Communication and Information Systems (ICCIS 2017). https://doi.org/10.1145/3158233.3159381
> optimize sm9 miller loop

- CMakeLists.txt
hi guanzhi, i'm tring to compile under win10 & clion & MinGW. while compiling under windows, socket function of send() and recv() is undefined.  I guess we should add link library ws2_32.[similar question on stackoverflow](https://stackoverflow.com/questions/2033608/mingw-linker-error-winsock)
> add link libraries ws2_32, fix win32 compile error.

- CMakeLists.txt
- tools/gmssl.c
- tools/sm2keyparse.c
在tools中增加了sm2keyparse部分，可以在命令行中以十六进制的明文形式查看SM2的公钥和私钥。
命令行中使用示例：
gmssl sm2keyparse -in sm2.pem -pass 1234
gmssl sm2keyparse -pubin sm2pub.pem
> 增加了sm2keyparse部分

- CMakeLists.txt
- demos/src/demo_sm2_public_key_parse.c
增加sm2 public key parse demo，通过标准输入输入sm2公钥pem文件，然后解析成sm2key结构体后将通过标准输出输出sm2key结构体的公钥
> 增加sm2 public key parse demo

- src/sm9_alg.c
优化了sm9_fp12_sqr()函数，相比原始方法，减少了一些运算。
优化方法来自文献[1]，将其中SQR3方法用于扩域Fp12 元素的平方运算。
[1]CHUNG J, HASAN M A. Asymmetric squaring formulae[C]. In: Proceedings of 18th IEEE Symposium on Computer Arithmetic (ARITH 2007). IEEE, 2007: 113–122. [DOI: 10.1109/ARITH.2007.11]
> 优化sm9_fp12_sqr()函数

- src/sm9_alg.c
优化了sm9中sm9_fp_mul函数，减少了不必要的运算。
经测试，该优化对sm9签名大约有10%的性能提升，下图分别为在github codespaces中使用优化前和优化后的sm9_fp_mul函数进行100次sm9签名的时间对比。
优化前：
优化后：
> optimize sm9_fp_mul

- src/sm2_alg.c
````
if ((y == 0x02 && sm2_bn_is_odd(_y)) || (y == 0x03) && !sm2_bn_is_odd(_y)) {
```
后半段的优先级应该加括号包起来
> fix: sm2_point_from_x函数内的表达式应该明确优先级

- src/sm2_z256.c
not include <gmssl/sm2_z256.h> in  src/sm2_z256.c
> Fix bug not including sm2_z256.h
